[project]
name = "gpu-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "diffusers>=0.35.1",
    "openai-whisper>=20250625",
    "pytest>=8.4.2",
    "sentence-transformers>=5.1.1",
    "torchvision>=0.23.0",
]
